---
- name: Install atop on all
  hosts: all
  ignore_errors: true
  tasks:
    - name: Install on CentOS
      when: ansible_os_family == "RedHat"
      package:
        name: epel-release


    - name: Install Epal
      when: ansible_os_family == "RedHat"
      package:
       name: atop


    - name: Install on Ubuntu
      when: ansible_os_family == "Debian"
      package:
        name: atop

    - name: Run atop to Ubuntu Daily
      when: ansible_os_family == "Debian"
      shell: "sed 's/600/60/' /etc/default/atop -i"


    - name: run  atop  every minute
      when:
        - ( 'ansible_os_family == "RedHat" and ansible_distribution_major_version "6"' )
        - ( 'ansible_os_family == "RedHat" and ansible_distribution_major_version "7"' )
      shell: "sed 's/600/60/' /etc/atop/atop.daly -i"


    - name: Start atop on RedHat 6
      when: ( 'ansible_os_family == "RedHat" and ansible_distribution_major_version "6"' )
      service:
        name: atop
        state: started
        enabled: yes


    - name: Start atop RedHat 7
      when: ( 'ansible_os_family == "RedHat" and ansible_distribution_major_version "7"' )
      systemd:
        name: atop
        state: started
        enabled: yes


    - name: Start atop on Ubuntu
      when: ( ansible_os_family == "Debian" )
      systemd:
        name: atop
        state: started
        enabled: yes
