---
- name: Change file content
  ignore_errors: true
  hosts: localhost
  tasks:
    - name: Change /tmp/file
      lineinfile:
        path: /tmp/file
        line: "hello"
        line: "hello word"
        create: yes
